services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: fpv_lists
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

volumes:
  pgdata: